ingress:
  enabled: true
  hosts:
    - grafana.hyperliquid.example
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local
        access: proxy
        isDefault: true

dashboardsConfigMaps:
  default: bot-assist-grafana-dashboards
