image:
  repository: ghcr.io/example/bot-assist
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

env: {}

livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 15
  timeoutSeconds: 5

readinessProbe:
  httpGet:
    path: /readyz
    port: http
  initialDelaySeconds: 10
  timeoutSeconds: 3

nodeSelector: {}
tolerations: []
affinity: {}

alerting:
  enabled: true
  latencyThreshold: 1
  errorRateThreshold: 0.05
